version: '3'
services:
  lize:
    build:
      context: .
    volumes:
      - ./:/front
    command: yarn dev
    networks:
      - common_link
    ports:
      - "3000:3000"
  toko:
    image: "ghcr.io/ruritoblogger/toko:latest"
  ange:
    image: "ghcr.io/ruritoblogger/ange:latest"

networks:
  common_link:
    external: true
